/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContentReturn {
  'headerImageUrl' : string,
  'body_fa' : string,
  'body_sv' : string,
}
export interface ActivityReturn {
  'id' : bigint,
  'regAllowedPhones' : Array<string>,
  'formTemplateId' : [] | [bigint],
  'body_fa' : string,
  'body_sv' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'createdAt' : bigint,
  'slug' : string,
  'regMaxRegistrationsPerPhone' : [] | [bigint],
  'regBlockDuplicateEmail' : boolean,
  'customFormFields' : Array<FormFieldReturn>,
  'imageUrl' : string,
  'sessions' : Array<EventSessionReturn>,
  'excerpt_fa' : string,
  'excerpt_sv' : string,
  'hasRegistration' : boolean,
  'regMaxCapacity' : [] | [bigint],
  'registrationMode' : string,
  'title_fa' : string,
  'title_sv' : string,
  'topicId' : bigint,
}
export interface ContactMessageReturn {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface EventRegistrationTemplateReturn {
  'id' : bigint,
  'description_fa' : string,
  'description_sv' : string,
  'createdAt' : bigint,
  'fields' : Array<FormFieldReturn>,
  'sessions' : Array<EventSessionReturn>,
  'name_fa' : string,
  'name_sv' : string,
}
export interface EventSessionReturn {
  'id' : bigint,
  'sortOrder' : bigint,
  'date' : string,
  'bufferCapacity' : bigint,
  'name_fa' : string,
  'name_sv' : string,
  'capacity' : bigint,
}
export interface FormFieldReturn {
  'id' : bigint,
  'minValue' : [] | [bigint],
  'sortOrder' : bigint,
  'label_fa' : string,
  'label_sv' : string,
  'isLookupField' : boolean,
  'placeholder_fa' : string,
  'placeholder_sv' : string,
  'required' : boolean,
  'maxValue' : [] | [bigint],
  'options' : Array<{ 'fa' : string, 'sv' : string }>,
  'fieldType' : string,
}
export interface FormTemplateReturn {
  'id' : bigint,
  'description_fa' : string,
  'description_sv' : string,
  'createdAt' : bigint,
  'fields' : Array<FormFieldReturn>,
  'name_fa' : string,
  'name_sv' : string,
}
export interface HeroSlideReturn {
  'id' : bigint,
  'ctaText_fa' : string,
  'ctaText_sv' : string,
  'sortOrder' : bigint,
  'subtitle_fa' : string,
  'subtitle_sv' : string,
  'ctaLink' : string,
  'imageUrl' : string,
  'title_fa' : string,
  'title_sv' : string,
  'topicId' : bigint,
}
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export type HttpToken = {};
export interface PageSeoOverride {
  'title' : string,
  'slug' : string,
  'description' : string,
  'lastModified' : string,
  'ogImage' : string,
  'noIndex' : boolean,
  'sitemapInclude' : boolean,
  'canonicalUrl' : string,
  'noFollow' : boolean,
  'jsonLd' : string,
  'sitemapPriority' : string,
  'sitemapChangefreq' : string,
}
export interface RegistrationFieldValueReturn {
  'value' : string,
  'fieldLabel' : string,
  'fieldId' : bigint,
}
export interface RegistrationReturn {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'fieldValues' : Array<RegistrationFieldValueReturn>,
  'activityId' : bigint,
  'selectedSessions' : Array<{ 'sessionName' : string, 'sessionId' : bigint }>,
  'email' : string,
  'message' : string,
  'personCount' : bigint,
  'phone' : string,
}
export interface RegistrationWithStatusReturn {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'fieldValues' : Array<
    { 'value' : string, 'fieldLabel' : string, 'fieldId' : bigint }
  >,
  'activityId' : bigint,
  'selectedSessions' : Array<SessionStatusReturn>,
  'email' : string,
  'personCount' : bigint,
  'phone' : string,
}
export interface SeoSettings {
  'defaultLang' : string,
  'defaultDescription' : string,
  'siteName' : string,
  'googleAnalyticsId' : string,
  'robotsTxtExtra' : string,
  'twitterCardType' : string,
  'defaultOgImage' : string,
  'bingVerification' : string,
  'twitterHandle' : string,
  'defaultTitle' : string,
  'googleVerification' : string,
  'titleTemplate' : string,
  'canonicalBaseUrl' : string,
}
export interface SessionAvailabilityReturn {
  'sortOrder' : bigint,
  'date' : string,
  'bufferCapacity' : bigint,
  'totalFull' : boolean,
  'regularFull' : boolean,
  'confirmedCount' : bigint,
  'name_fa' : string,
  'name_sv' : string,
  'sessionId' : bigint,
  'capacity' : bigint,
  'bufferCount' : bigint,
}
export interface SessionStatsReturn {
  'sortOrder' : bigint,
  'date' : string,
  'bufferCapacity' : bigint,
  'confirmedCount' : bigint,
  'name_fa' : string,
  'name_sv' : string,
  'sessionId' : bigint,
  'capacity' : bigint,
  'bufferCount' : bigint,
  'registrationCount' : bigint,
}
export interface SessionStatusReturn {
  'status' : string,
  'sessionName' : string,
  'sessionId' : bigint,
}
export interface SiteSettingsReturn {
  'landingBackgroundUrl' : string,
  'topicsBackgroundUrl' : string,
  'subtitle_fa' : string,
  'subtitle_sv' : string,
  'logoUrl' : string,
  'mockMode' : boolean,
  'title_fa' : string,
  'title_sv' : string,
}
export interface SocialLinkReturn {
  'id' : bigint,
  'url' : string,
  'sortOrder' : bigint,
  'platform' : string,
}
export interface StreamingCallbackResponse {
  'token' : [] | [HttpToken],
  'body' : Uint8Array,
}
export type StreamingStrategy = {
    'Callback' : { 'token' : HttpToken, 'callback' : [Principal, string] }
  };
export type SubmitRegistrationResult = { 'ok' : RegistrationWithStatusReturn } |
  { 'invalidInput' : null } |
  { 'duplicateEmail' : null } |
  { 'capacityFull' : null } |
  { 'sessionsUnavailable' : Array<bigint> } |
  { 'phoneNotAllowed' : null } |
  { 'registrationDisabled' : null } |
  { 'maxRegistrationsReached' : null };
export interface TopicReturn {
  'id' : bigint,
  'description_fa' : string,
  'description_sv' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'createdAt' : bigint,
  'slug' : string,
  'backgroundUrl' : string,
  'title_fa' : string,
  'title_sv' : string,
}
export interface _SERVICE {
  'adminLogin' : ActorMethod<[string], [] | [string]>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'cancelRegistration' : ActorMethod<[bigint, string], boolean>,
  'changePassword' : ActorMethod<[string, string], boolean>,
  'checkSession' : ActorMethod<[string], boolean>,
  'createActivity' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      string,
      [] | [bigint],
      Array<FormFieldReturn>,
      Array<EventSessionReturn>,
      [] | [bigint],
      Array<string>,
      [] | [bigint],
      boolean,
      bigint,
    ],
    ActivityReturn
  >,
  'createEventRegistrationTemplate' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<EventSessionReturn>,
      Array<FormFieldReturn>,
    ],
    EventRegistrationTemplateReturn
  >,
  'createFormTemplate' : ActorMethod<
    [string, string, string, string, string, Array<FormFieldReturn>],
    FormTemplateReturn
  >,
  'createSlide' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
    ],
    HeroSlideReturn
  >,
  'createSocialLink' : ActorMethod<
    [string, string, string, bigint],
    SocialLinkReturn
  >,
  'createTopic' : ActorMethod<
    [string, string, string, string, string, string, string, string, bigint],
    TopicReturn
  >,
  'deleteActivity' : ActorMethod<[string, bigint], boolean>,
  'deleteAsset' : ActorMethod<[string, string], boolean>,
  'deleteContactMessage' : ActorMethod<[string, bigint], boolean>,
  'deleteEventRegistrationTemplate' : ActorMethod<[string, bigint], boolean>,
  'deleteFormTemplate' : ActorMethod<[string, bigint], boolean>,
  'deletePageSeoOverride' : ActorMethod<[string, string], undefined>,
  'deleteSlide' : ActorMethod<[string, bigint], boolean>,
  'deleteSocialLink' : ActorMethod<[string, bigint], boolean>,
  'deleteTopic' : ActorMethod<[string, bigint], boolean>,
  'getAboutContent' : ActorMethod<[], AboutContentReturn>,
  'getActivitiesByTopic' : ActorMethod<[bigint], Array<ActivityReturn>>,
  'getActivity' : ActorMethod<[bigint], [] | [ActivityReturn]>,
  'getActivityBySlug' : ActorMethod<[bigint, string], [] | [ActivityReturn]>,
  'getActivityFormFields' : ActorMethod<
    [bigint],
    [] | [Array<FormFieldReturn>]
  >,
  'getAllActivities' : ActorMethod<[], Array<ActivityReturn>>,
  'getAllRegistrations' : ActorMethod<[string], Array<RegistrationReturn>>,
  'getAsset' : ActorMethod<[string], [] | [Uint8Array]>,
  'getContactMessages' : ActorMethod<[string], Array<ContactMessageReturn>>,
  'getEventRegistrationTemplate' : ActorMethod<
    [bigint],
    [] | [EventRegistrationTemplateReturn]
  >,
  'getEventRegistrationTemplates' : ActorMethod<
    [],
    Array<EventRegistrationTemplateReturn>
  >,
  'getFormTemplate' : ActorMethod<[bigint], [] | [FormTemplateReturn]>,
  'getFormTemplates' : ActorMethod<[], Array<FormTemplateReturn>>,
  'getPageSeoOverride' : ActorMethod<[string], [] | [PageSeoOverride]>,
  'getRegistrationById' : ActorMethod<
    [bigint, string],
    [] | [RegistrationWithStatusReturn]
  >,
  'getRegistrations' : ActorMethod<[string, bigint], Array<RegistrationReturn>>,
  'getRobotsTxt' : ActorMethod<[], string>,
  'getSeoSettings' : ActorMethod<[], SeoSettings>,
  'getSessionAvailability' : ActorMethod<
    [bigint],
    Array<SessionAvailabilityReturn>
  >,
  'getSessionStats' : ActorMethod<[string, bigint], Array<SessionStatsReturn>>,
  'getSettings' : ActorMethod<[], SiteSettingsReturn>,
  'getSitemapXml' : ActorMethod<[], string>,
  'getSlidesByTopic' : ActorMethod<[bigint], Array<HeroSlideReturn>>,
  'getSocialLinks' : ActorMethod<[], Array<SocialLinkReturn>>,
  'getTopic' : ActorMethod<[bigint], [] | [TopicReturn]>,
  'getTopicBySlug' : ActorMethod<[string], [] | [TopicReturn]>,
  'getTopics' : ActorMethod<[], Array<TopicReturn>>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'listAssets' : ActorMethod<[], Array<string>>,
  'listPageSeoOverrides' : ActorMethod<[string], Array<PageSeoOverride>>,
  'modifyRegistration' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      Array<bigint>,
      Array<{ 'value' : string, 'fieldId' : bigint }>,
    ],
    SubmitRegistrationResult
  >,
  'setMockMode' : ActorMethod<[string, boolean], boolean>,
  'setPageSeoOverride' : ActorMethod<[string, PageSeoOverride], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    [] | [ContactMessageReturn]
  >,
  'submitRegistration' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      Array<bigint>,
      Array<{ 'value' : string, 'fieldId' : bigint }>,
    ],
    SubmitRegistrationResult
  >,
  'updateAboutContent' : ActorMethod<
    [string, string, string, string],
    AboutContentReturn
  >,
  'updateActivity' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      string,
      [] | [bigint],
      Array<FormFieldReturn>,
      Array<EventSessionReturn>,
      [] | [bigint],
      Array<string>,
      [] | [bigint],
      boolean,
      bigint,
    ],
    [] | [ActivityReturn]
  >,
  'updateEventRegistrationTemplate' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      Array<EventSessionReturn>,
      Array<FormFieldReturn>,
    ],
    [] | [EventRegistrationTemplateReturn]
  >,
  'updateFormTemplate' : ActorMethod<
    [string, bigint, string, string, string, string, Array<FormFieldReturn>],
    [] | [FormTemplateReturn]
  >,
  'updateSeoSettings' : ActorMethod<[string, SeoSettings], undefined>,
  'updateSettings' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    SiteSettingsReturn
  >,
  'updateSlide' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
    ],
    [] | [HeroSlideReturn]
  >,
  'updateSocialLink' : ActorMethod<
    [string, bigint, string, string, bigint],
    [] | [SocialLinkReturn]
  >,
  'updateTopic' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
    ],
    [] | [TopicReturn]
  >,
  'uploadAsset' : ActorMethod<[string, string, string, Uint8Array], string>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];