/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const ActivityReturn = IDL.Record({
    'id' : IDL.Nat,
    'body_fa' : IDL.Text,
    'body_sv' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt_fa' : IDL.Text,
    'excerpt_sv' : IDL.Text,
    'hasRegistration' : IDL.Bool,
    'title_fa' : IDL.Text,
    'title_sv' : IDL.Text,
    'topicId' : IDL.Nat,
  });
  const HeroSlideReturn = IDL.Record({
    'id' : IDL.Nat,
    'ctaText_fa' : IDL.Text,
    'ctaText_sv' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'subtitle_fa' : IDL.Text,
    'subtitle_sv' : IDL.Text,
    'ctaLink' : IDL.Text,
    'imageUrl' : IDL.Text,
    'title_fa' : IDL.Text,
    'title_sv' : IDL.Text,
    'topicId' : IDL.Nat,
  });
  const SocialLinkReturn = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'platform' : IDL.Text,
  });
  const TopicReturn = IDL.Record({
    'id' : IDL.Nat,
    'description_fa' : IDL.Text,
    'description_sv' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'backgroundUrl' : IDL.Text,
    'title_fa' : IDL.Text,
    'title_sv' : IDL.Text,
  });
  const AboutContentReturn = IDL.Record({
    'headerImageUrl' : IDL.Text,
    'body_fa' : IDL.Text,
    'body_sv' : IDL.Text,
  });
  const RegistrationReturn = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'activityId' : IDL.Nat,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactMessageReturn = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SiteSettingsReturn = IDL.Record({
    'landingBackgroundUrl' : IDL.Text,
    'topicsBackgroundUrl' : IDL.Text,
    'subtitle_fa' : IDL.Text,
    'subtitle_sv' : IDL.Text,
    'logoUrl' : IDL.Text,
    'title_fa' : IDL.Text,
    'title_sv' : IDL.Text,
  });
  
  return IDL.Service({
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'checkSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createActivity' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
        ],
        [ActivityReturn],
        [],
      ),
    'createSlide' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [HeroSlideReturn],
        [],
      ),
    'createSocialLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [SocialLinkReturn],
        [],
      ),
    'createTopic' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [TopicReturn],
        [],
      ),
    'deleteActivity' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteAsset' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteContactMessage' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteSlide' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteSocialLink' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteTopic' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getAboutContent' : IDL.Func([], [AboutContentReturn], ['query']),
    'getActivitiesByTopic' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityReturn)],
        ['query'],
      ),
    'getActivity' : IDL.Func([IDL.Nat], [IDL.Opt(ActivityReturn)], ['query']),
    'getActivityBySlug' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(ActivityReturn)],
        ['query'],
      ),
    'getAllActivities' : IDL.Func([], [IDL.Vec(ActivityReturn)], ['query']),
    'getAllRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RegistrationReturn)],
        ['query'],
      ),
    'getAsset' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
    'getContactMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactMessageReturn)],
        ['query'],
      ),
    'getRegistrations' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(RegistrationReturn)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [SiteSettingsReturn], ['query']),
    'getSlidesByTopic' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HeroSlideReturn)],
        ['query'],
      ),
    'getSocialLinks' : IDL.Func([], [IDL.Vec(SocialLinkReturn)], ['query']),
    'getTopic' : IDL.Func([IDL.Nat], [IDL.Opt(TopicReturn)], ['query']),
    'getTopicBySlug' : IDL.Func([IDL.Text], [IDL.Opt(TopicReturn)], ['query']),
    'getTopics' : IDL.Func([], [IDL.Vec(TopicReturn)], ['query']),
    'listAssets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(ContactMessageReturn)],
        [],
      ),
    'submitRegistration' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(RegistrationReturn)],
        [],
      ),
    'updateAboutContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AboutContentReturn],
        [],
      ),
    'updateActivity' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
        ],
        [IDL.Opt(ActivityReturn)],
        [],
      ),
    'updateSettings' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [SiteSettingsReturn],
        [],
      ),
    'updateSlide' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Opt(HeroSlideReturn)],
        [],
      ),
    'updateSocialLink' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(SocialLinkReturn)],
        [],
      ),
    'updateTopic' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Opt(TopicReturn)],
        [],
      ),
    'uploadAsset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };